# Generated by Django 4.2.3 on 2023-08-06 11:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=200, null=True, verbose_name='Code')),
                ('Description', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('CodeType', models.CharField(max_length=200, null=True, verbose_name='CodeType')),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
            ],
        ),
    ]
