# Generated by Django 4.2.3 on 2023-08-07 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0002_delete_standardcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
                ('code', models.CharField(max_length=200, null=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(null=True, verbose_name='IsActive')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
