# Generated by Django 4.2.3 on 2023-08-07 07:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
                ('code', models.CharField(max_length=200, null=True, verbose_name='Code')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('code_type', models.CharField(max_length=200, null=True, verbose_name='CodeType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
                ('code', models.CharField(max_length=200, null=True, verbose_name='Code')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.country')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
