# Generated by Django 4.2.3 on 2023-08-07 07:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_standardcode_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
                ('major', models.CharField(max_length=200, null=True, verbose_name='Major')),
                ('university', models.CharField(max_length=200, null=True, verbose_name='University')),
                ('year', models.IntegerField(null=True, verbose_name='Year')),
                ('gpa', models.IntegerField(null=True, verbose_name='GPA')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.country')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.standardcode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
