# Generated by Django 4.2.3 on 2023-08-07 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_candidatecertification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
                ('employer_name', models.CharField(max_length=200, null=True, verbose_name='EmployerName')),
                ('from_date', models.DateField(null=True, verbose_name='FromDate')),
                ('to_date', models.DateField(null=True, verbose_name='ToDate')),
                ('position', models.CharField(max_length=200, null=True, verbose_name='Position')),
                ('reason_for_leaving', models.CharField(max_length=500, null=True, verbose_name='ReasonForLeaving')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
