# Generated by Django 4.2.3 on 2023-08-07 08:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_candidateexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
                ('years_of_experience', models.CharField(max_length=200, null=True, verbose_name='YearsOfExperience')),
                ('last_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.standardcode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
