# Generated by Django 4.2.3 on 2023-08-07 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_candidatelanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatelanguage',
            name='proficiency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_primary_candidate_language', to='mainapp.standardcode', verbose_name='proficiency'),
        ),
        migrations.AlterField(
            model_name='candidatelanguage',
            name='last_used',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_secondary_candidate_language', to='mainapp.standardcode', verbose_name='last_used'),
        ),
    ]
