# Generated by Django 4.2.3 on 2023-08-07 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_candidatelanguage_proficiency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country_id',
            new_name='country',
        ),
    ]
