# Generated by Django 4.2.3 on 2023-08-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0016_remove_customuser_certification_and_more'),
        ('mainapp', '0011_city_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CandidateCertification',
        ),
        migrations.RemoveField(
            model_name='candidateeducation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='candidateeducation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='candidateeducation',
            name='degree',
        ),
        migrations.DeleteModel(
            name='CandidateExperience',
        ),
        migrations.RemoveField(
            model_name='candidatelanguage',
            name='last_used',
        ),
        migrations.RemoveField(
            model_name='candidatelanguage',
            name='proficiency',
        ),
        migrations.DeleteModel(
            name='CandidateEducation',
        ),
        migrations.DeleteModel(
            name='CandidateLanguage',
        ),
    ]
