# Generated by Django 4.2.3 on 2023-08-25 13:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_homeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='CreatedDate')),
                ('Name', models.CharField(max_length=200, null=True, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homeimage',
            name='ConfidenceJson',
            field=models.CharField(max_length=400, null=True, verbose_name='ConfidenceJson'),
        ),
        migrations.AddField(
            model_name='homeimage',
            name='Status',
            field=models.IntegerField(null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='homeimage',
            name='Segment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.segment'),
        ),
    ]
