# Generated by Django 4.2.3 on 2023-08-07 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_candidatelanguage_proficiency_and_more'),
        ('authapp', '0007_customuser_passport_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_primary_custom_user', to='mainapp.standardcode'),
        ),
    ]
