# Generated by Django 4.2.3 on 2023-08-07 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_candidatelanguage_proficiency_and_more'),
        ('authapp', '0008_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='certification',
            field=models.ManyToManyField(to='mainapp.candidatecertification'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.ManyToManyField(to='mainapp.candidateeducation'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience',
            field=models.ManyToManyField(to='mainapp.candidateexperience'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.ManyToManyField(to='mainapp.candidatelanguage'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marital_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_tertiary_standardcode', to='mainapp.standardcode'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_secondary_standardcode', to='mainapp.standardcode'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_primary_standardcode', to='mainapp.standardcode'),
        ),
    ]
