# Generated by Django 4.2.3 on 2023-08-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_customuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image_path',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
