# Generated by Django 4.2.3 on 2023-08-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0012_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_try',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
